---

- name: Restart consul service
  command: docker-compose up -d
  args:
    chdir: "{{ consul.service_dir }}"
  listen: "restart consul"

- name: Update consul config  # noqa 305
  shell: docker kill -s HUP {{ consul.container.name }}
  listen: "reload consul"
