---

- name: Converge
  hosts: all
  become: true

  vars:
    env: develop

    services_dir: /opt/services

    private_network: "{{ ansible_eth0['ipv4'] }}"

    consul:
      agent:
        server: yes
        encrypt: SXlrC5I3W8s5Y1KT+H5xFsodZb1n4vhV

        servers:
          - instance

  roles:
    - role: dnsmasq
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
    - name: Add services to Consul Catalog
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
        tasks_from: services
      vars:
        services:
          - name: postgresql
            entries:
              - name: postgresql
                host: 127.0.0.1
                port: 5432
                tags:
                  - "{{ env }}"
                meta:
                  hostname: "{{ ansible_hostname }}"
                  tier: "{{ env }}"

    - name: Install test requirements
      apt: name=curl
